import { CheckoutFlowID, CheckoutSessionID, DriveID, JobRunID, JobRunStatus, UserID } from "@officexapp/types";
import { v4 as uuidv4 } from "uuid";

export enum IDPrefixEnum {
  CustomerPurchase = "CustomerPurchaseID_",
  CheckoutWallet = "CheckoutWalletID_",
  Offer = "OfferID_",
  CheckoutSession = "CheckoutSessionID_",
  Tracer = "TracerID_",
}

export const GenerateID = {
  CustomerPurchase: () => `${IDPrefixEnum.CustomerPurchase}${uuidv4()}`,
  CheckoutWallet: () => `${IDPrefixEnum.CheckoutWallet}${uuidv4()}`,
  Offer: () => `${IDPrefixEnum.Offer}${uuidv4()}`,
  CheckoutSession: () => `${IDPrefixEnum.CheckoutSession}${uuidv4()}`,
  Tracer: () => `${IDPrefixEnum.Tracer}${uuidv4()}`,
};

export type CustomerPurchaseID = string;
export type CheckoutWalletID = string;
export type OfferID = string;
export type TracerID = string;

// deposit wallets can get created before a purchase
// deposit wallets can get abandoned on checkout
// this reside in postgres
export interface CheckoutWallet {
  id: CheckoutWalletID;
  title: string;
  description: string;
  evm_address: string;
  private_key: string;
  seed_phrase: string;
  latest_usd_balance: number; // 6 decimals
  created_at: number;
  updated_at: number;
  offer_id: OfferID;
  checkout_flow_id: CheckoutFlowID;
  checkout_session_id: CheckoutSessionID;
  tracer?: string;
  metadata?: Record<string, any>; // Changed from 'string' to 'Record<string, any>' for JSONB
  purchase_id?: CustomerPurchaseID;
  offramp_evm_address?: string;
}

// this resides in postgres
export interface Offer {
  id: OfferID;
  sku: string;
  title: string;
  description: string;
  created_at: number;
  updated_at: number;
  metadata?: Record<string, any>; // Changed from 'JSON' to 'Record<string, any>' for JSONB
}

// this resides in postgres
export interface CustomerPurchase {
  id: CustomerPurchaseID;
  wallet_id: CheckoutWalletID;
  officex_purchase_id: JobRunID;
  title: string;
  description: string;
  customer_user_id: UserID;
  customer_org_id: DriveID;
  customer_org_endpoint: string;
  vendor_id: UserID;
  price_line: string;
  customer_check_billing_api_key: string;
  vendor_update_billing_api_key: string;
  vendor_notes: string;
  balance: number;
  balance_low_trigger: number;
  balance_critical_trigger: number;
  balance_termination_trigger: number;
  created_at: number;
  updated_at: number;
  tracer?: string;
  metadata?: Record<string, any>; // Changed from 'string' to 'Record<string, any>' for JSONB
}

// this is simply saved as a json file, not in database
export interface AboutVendor {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  endpoint: string;
}

// Define a type for UsageRecord that includes the auto-generated 'id'
// and uses Date for timestamp for easier handling in JS
export interface UsageRecord {
  id?: number; // Auto-generated by DB
  purchase_id: CustomerPurchaseID;
  timestamp: Date; // Use Date object for TIMESTAMPTZ
  usage_amount: number;
  unit: string;
  cost_incurred: number;
  description?: string;
  metadata?: Record<string, any>; // JSONB type
}

// Interface for historical billing report results
export interface HistoricalBillingEntry {
  time_bucket: Date; // The start of the time bucket
  total_usage_amount: number;
  total_cost_incurred: number;
  purchase_id: CustomerPurchaseID;
}
